app/controllers/database_controller.py
import json
import os

from flask import request, redirect, url_for, session, make_response, jsonify
from flask import Blueprint, render_template
from datetime import datetime

from app import AUTHENTICATED_ROLE, patreon_service
from app.annotations.authenticatedAnnotation import Authenticated
from app.annotations.requiredParamsAnnotation import RequiredParams
from app.language import words
from app.services.interfaces.idatabase_service import DatabaseService
from app.utils.singleton import Singleton


class DatabaseController(Singleton):
    blueprint = Blueprint('database', __name__)
    service: DatabaseService = None

    @staticmethod
    @blueprint.route('/facts/create', methods=['POST'])
    @Authenticated(required_roles=[AUTHENTICATED_ROLE])
    @RequiredParams()
    def createFact(title: str, context: str, page: int, quote: str, source_id: str, authentication: dict = None):
        user_id = authentication.get('sub')

        from run import csrf  # Import here to avoid circular import
        csrf.protect()

        if any(len(s) > 512 for s in [title, context, source_id]):
            return {'error': 'Some field is too long!'}, 422
        if len(quote) > 1024:
            return {'error': 'Some field is too long!'}, 422

        existing_fact = DatabaseController.service.get_document('facts', {'title': title})
        if existing_fact:
            return {'error': 'Fact with that name exists.'}, 403

        user_facts_count = DatabaseController.service.count_documents('facts', {'user_id': user_id})
        if user_facts_count >= int(os.getenv('FACTS_MAX_COUNT_DEFAULT', 10)):
            patreon_access_token = request.cookies.get('patreon_access_token', None)
            if patreon_access_token:
                user_cents = patreon_service.get_user_cents()
                if user_cents >= int(os.getenv('FACTS_CENTS_SUBSCRIBER', 100)):
                    if user_facts_count >= int(os.getenv('FACTS_MAX_COUNT_SUBSCRIBER', 100)):
                        return redirect(url_for('web.pleaseSubscribe', text=words[request.cookies.get('lang', 'en')]['max_subscriber'].replace('*', os.getenv("FACTS_MAX_COUNT_DEFAULT", 100))))
                else:
                    return redirect(url_for('web.pleaseSubscribe', text=words[request.cookies.get('lang', 'en')]['not_subscriber'].replace('*',os.getenv("FACTS_MAX_COUNT_DEFAULT", 10))))
            else:
                return redirect(url_for('web.pleaseSubscribe', text=words[request.cookies.get('lang', 'en')]['not_subscriber'].replace('*', os.getenv("FACTS_MAX_COUNT_DEFAULT", 10))))

        fact = DatabaseController.service.create_fact(title=title,
                                                      context=context,
                                                      page=page,
                                                      quote=quote,
                                                      source_id=source_id,
                                                      user_id=user_id)
        return redirect(f'/facts?_id={fact.get("_id", "")}')

    @staticmethod
    @blueprint.route('/facts/delete', methods=['POST'])
    @Authenticated(required_roles=[AUTHENTICATED_ROLE])
    @RequiredParams()
    def deleteFact(fact_id: str, authentication: dict = None):
        from run import csrf  # Import here to avoid circular import
        csrf.protect()

        user_id = authentication.get('sub', None)
        fact = DatabaseController.service.get_document('facts', {'_id': fact_id})
        if user_id and fact and user_id == fact.get('user_id', None):
            DatabaseController.service.delete_document('facts', {'_id': fact.get('_id', None)})
            referrer = request.referrer
            allowed_hosts = [os.getenv('HOST')]
            if referrer and any(
                    referrer.startswith(f"{host}") for host in
                    allowed_hosts):
                return redirect(referrer)
            return redirect(url_for('web.home'))
        else:
            return {'error': 'Wrong data'}, 422

    @staticmethod
    @blueprint.route('/sources/create', methods=['POST'])
    @Authenticated(required_roles=[AUTHENTICATED_ROLE])
    @RequiredParams()
    def createSource(title: str, author: str, year: int, _type_id: str, link: str, authentication: dict = None):
        from run import csrf  # Import here to avoid circular import
        csrf.protect()

        user_id = authentication.get('sub')

        if any(len(s) > 512 for s in [title, author, _type_id, link]):
            return {'error': 'Some field is too long!'}, 422

        existing_source = DatabaseController.service.get_document('sources', {'title': title})
        if existing_source:
            return {'error': 'Source is already exists.'}, 403

        if DatabaseController.service.count_documents('sources', {}) >= int(os.getenv('SOURCES_MAX_COUNT', 10000)):
            return {'error': 'Too many sources on server!'}, 403

        source = DatabaseController.service.create_source(title=title,
                                                          author=author,
                                                          year=year,
                                                          _type_id=_type_id,
                                                          link=link)
        return redirect(f'/sources?_id={source.get("_id", "")}')

    @staticmethod
    @blueprint.route('/react', methods=['POST'])
    @Authenticated(required_roles=[AUTHENTICATED_ROLE])
    @RequiredParams()
    def react(authentication: dict = None):
        from run import csrf  # Import here to avoid circular import
        csrf.protect()

        data = request.get_json()
        if not data:
            return jsonify({"error": "Invalid JSON data"}), 400

        _id = data.get('_id')
        _collection = data.get('_collection')
        _label = data.get('_label')
        if not _id or not _collection or not _label:
            return jsonify({"error": "Invalid JSON data"}), 400

        user_id = authentication.get('sub')

        return {"response": DatabaseController.service.react(_id, _collection, _label, user_id)}

app/controllers/image_controller.py
from flask import Blueprint, send_file

from app.services.interfaces.iimage_service import ImageService
from app.utils.singleton import Singleton


class ImageController(Singleton):
    blueprint = Blueprint('image', __name__)
    service: ImageService = None

    @staticmethod
    @blueprint.route('/avatar/<username>', methods=['GET'])
    def getAvatar(username: str = 'default'):
        if username == 'default':
            return send_file(ImageController.service.get_default(), mimetype='image/png')
        """Serve the generated avatar image."""
        img_io = ImageController.service.get_avatar(username)
        return send_file(img_io, mimetype='image/png')

app/templates/cards.html
{% extends 'index.html' %}

{% block title %}{{ _words['logo'] }}: {{ title }}{% endblock %}

{% block content %}

<h2 class="mb-3">{{ title }}</h2>

<!-- Filter Form -->
    <div class="mb-3">
        <div class="row g-2">

            <div class="col-md-3">
            {% if redirect == 'web.factsView' %}
                <input type="text" id="username" class="form-control" placeholder="{{ _words['username'] }}" value="{{ request.args.get('username', '') }}">
            {% else %}
                <input type="text" id="author" class="form-control" placeholder="{{ _words['author'] }}" value="{{ request.args.get('username', '') }}">
            {% endif %}
             </div>

            <div class="col-md-3">
                <input type="text" id="title" class="form-control" placeholder="{{ _words['title'] }}" value="{{ request.args.get('title', '') }}">
            </div>
            <div class="col-md-2">
                <input type="number" id="year" class="form-control" placeholder="{{ _words['year'] }}" value="{{ request.args.get('year', '') }}">
            </div>
            <div class="col-md-2">
                <button id="apply-filters" class="btn btn-primary w-100 m-0" style="margin-top: 5px!important;">{{ _words['apply_filters'] }}</button>
            </div>
        </div>
    </div>

<!-- Cards -->
<div class="row">
    {% for card in cards %}
    <div class="col-md-4 mb-3">
        <a href="{{ url_for(redirect, _id=card._id) }}" style="text-decoration: none;">
        <div class="card">
            <div class="card-body d-flex flex-column flex-grow-1">
                <div class="row mb-2" style="margin-left: 0px;">
                    <div class="col-md-6 text-end" style="width: 32px; height: 32px; padding: 0 0;">
                        <img class="avatar w-16 h-16" src="{{ url_for('image.getAvatar', username=card.user.username) }}" alt="{{ _words['user_avatar'] }}">
                    </div>
                    <div class="col-md-6 d-flex flex-column justify-content-center">
                        <h6 class="card-subtitle text-muted">{{ card.user.username }}</h6>
                    </div>
                </div>
                <h6 class="card-title">{{ card.title }}</h6>
                <div>
                    <span class="badge text-white px-2 py-1 rounded" style="background-color: {{ card.type.color }};">{{ card.type.name }}</span><br>
                </div>
                <div class="mt-auto">
                <p class="card-text text-muted small"><strong>{{ _words['created_at'] }}:</strong> {{ card.created_at }}</p>
                {% for label in card.labels_ %}
                    <span class="badge bg-gray" style="color: {{label.color}}; border: 1px solid {{label.color}};" data-bs-toggle="tooltip" title="{{ _words.get(label.name, label.name) }}">{{ label.icon | safe }} {{ label.count }}</span>
                {% endfor %}
                </div>
            </div>
        </div>
        </a>
    </div>
    {% endfor %}
    {% if cards == [] %}
    <p>{{ _words['no_results'] }}</p>
    {% endif %}
</div>

{% endblock %}

{% block footer %}

<footer class="footer">
    <div class="container d-flex justify-content-center align-items-center gap-2">
        <nav aria-label="Page navigation">
            <ul class="pagination mb-0">
                {% if page > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1&limit={{ limit }}&sort={{ request.args.get('sort', 'year') }}&sort_order={{ request.args.get('sort_order', 'desc') }}{% for key in ['username', 'title', 'year'] %}{% if request.args.get(key) %}&{{ key }}={{ request.args.get(key) }}{% endif %}{% endfor %}" aria-label="First">
                            <i class="fa fa-angle-double-left"></i> {{ _words['first'] }}
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page-1 }}&limit={{ limit }}&sort={{ request.args.get('sort', 'year') }}&sort_order={{ request.args.get('sort_order', 'desc') }}{% for key in ['username', 'title', 'year'] %}{% if request.args.get(key) %}&{{ key }}={{ request.args.get(key) }}{% endif %}{% endfor %}" aria-label="Previous">
                            <i class="fa fa-angle-left"></i> {{ _words['previous'] }}
                        </a>
                    </li>
                {% endif %}

                <li class="page-item disabled">
                    <a class="page-link">{{ _words['page'] }} {{ page }} {{ _words['of'] }} {{ total_pages }}</a>
                </li>

                {% if page < total_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page+1 }}&limit={{ limit }}&sort={{ request.args.get('sort', 'year') }}&sort_order={{ request.args.get('sort_order', 'desc') }}{% for key in ['username', 'title', 'year'] %}{% if request.args.get(key) %}&{{ key }}={{ request.args.get(key) }}{% endif %}{% endfor %}" aria-label="Next">
                            {{ _words['next'] }} <i class="fa fa-angle-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ total_pages }}&limit={{ limit }}&sort={{ request.args.get('sort', 'year') }}&sort_order={{ request.args.get('sort_order', 'desc') }}{% for key in ['username', 'title', 'year'] %}{% if request.args.get(key) %}&{{ key }}={{ request.args.get(key) }}{% endif %}{% endfor %}" aria-label="Last">
                            {{ _words['last'] }} <i class="fa fa-angle-double-right"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        <div class="sort-options d-flex align-items-center">
            <span class="me-2">{{ _words['sort_by'] }}:</span>
            {% set labels_name = [_words['title'], _words['created_at']] %}
            {% set labels_ = [] %}
            {% set label_icons = [] %}
            {% set label_colors = [] %}
            {% for item in labels %}
                {% set _ = labels_.append(item.get('name', '')) %}
                {% set _ = label_icons.append(item.get('icon', None)) %}
                {% set _ = label_colors.append(item.get('color', None)) %}
            {% endfor %}
            {% for field in ['title', 'created_at'] + labels_ %}
                {% set current_sort = request.args.get('sort', 'created_at') %}
                {% set current_order = request.args.get('sort_order', 'desc') %}
                {% set new_order = 'asc' if current_sort == field and current_order == 'desc' else 'desc' %}

               <a href="?page={{ page }}&limit={{ limit }}&sort={{ field }}&sort_order={{ new_order }}{% for key in ['username', 'created_at'] %}{% if request.args.get(key) %}&{{ key }}={{ request.args.get(key) }}{% endif %}{% endfor %}"
                   class="btn btn-outline-secondary btn-sm" style="border-color: {{(label_colors[loop.index0 - 2] if loop.index0 >= 2)}}" title="{{ _words.get(field, field) }}">
                    <i class="fa
                       {% if current_sort == field and current_order == 'asc' %}fa-sort-up{% else %}fa-sort-down{% endif %}"
                       style="position: relative; {% if current_sort == field and current_order == 'asc' %}top: 2px;{% else %}top: -2px;{% endif %} color: {{(label_colors[loop.index0 - 2] if loop.index0 >= 2)}}">
                    </i>
                   <span class="ms-2">{{ (label_icons[loop.index0 - 2] if loop.index0 >= 2 else labels_name[loop.index0]) | safe }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
</footer>

<script nonce="{{ _nonce }}">
        document.getElementById("apply-filters").addEventListener("click", applyFilters);

        function updateSorting(field) {
            const urlParams = new URLSearchParams(window.location.search);
            let currentOrder = urlParams.get('sort_order') || 'desc';

            // Toggle sorting order
            let newOrder = (currentOrder === 'desc') ? 'asc' : 'desc';
            urlParams.set('sort', field);
            urlParams.set('sort_order', newOrder);

            window.location.search = urlParams.toString();
        }

        function applyFilters() {
            {% if redirect == 'web.factsView' %}
            const username = document.getElementById('username').value;
            {% else %}
            const username = document.getElementById('author').value;
            {% endif %}
            const title = document.getElementById('title').value;
            const year = document.getElementById('year').value;

            const urlParams = new URLSearchParams(window.location.search);
            if (username) urlParams.set('username', username);
            else urlParams.delete('username');

            if (title) urlParams.set('title', title);
            else urlParams.delete('title');

            if (year) urlParams.set('year', year);
            else urlParams.delete('year');

            window.location.search = urlParams.toString();
        }
    </script>

{% endblock %}

app/templates/fact.html
{% extends 'index.html' %}

{% block title %}{{ _words['logo'] }}: {{ _words['fact'] }}{% endblock %}

{% block content %}

<div class="container">
    <div class="card source-card">
        {% if fact.user_id == self_user_id  %}
        <form id="deleteFactForm" method="POST" class="position-absolute" style="top: 10px; right: 10px;">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input type="hidden" name="fact_id" value="{{ fact._id }}">
            <button type="submit" class="btn btn-danger" style="text-decoration: none!important; color: white!important;" style="
                top: 10px;
                right: 10px;
                text-decoration: none!important;
                color: white!important;">
                <i class="fas fa-times"></i>
            </button>
        </form>
        <div class="m-4"></div>
        {% endif %}


        <div class="p-4">
        <h3 class="text-primary">{{ fact.title }}</h3>
        <p><strong>{{ _words['context'] }}</strong></p>
        <p>{{ fact.context }}</p>
            </div>

        <div class="bg-gray text-muted m-0 p-0">
            <blockquote class="text-muted p-4">"{{ fact.quote }}" ({{ source.author }}, {{ source.year }}, {{ _words['p'] }}. {{ fact.page }})</blockquote>
        </div>

        <a href="{{ url_for('web.sourcesView', _id=source._id) }}" style="text-decoration: none;">
            <div class="p-4">
                <span class="badge text-white px-2 py-1 rounded" style="background-color: {{ type.color }};">{{ type.name }}</span>
                <i class="fa-solid fa-up-right-from-square"></i>
                <span style="color: black;">({{ source.author }}, {{ source.year }}, {{ source.title }})</span>
            </div>
        </a>

        <button id="copy-button" class="btn copy-btn m-0 p-4">
            <span class="icon"><i class="fa-solid fa-copy"></i></span><p>Copy</p>
        </button>

        <div class="p-4">
        <div class="mt-auto mt-3">
            <a href="{{ _host }}/profile/{{ user.username }}" style="text-decoration:none">
            <div class="row mb-2" style="margin-left: 0px;">
                    <div class="col-md-6 text-end" style="width: 32px; height: 32px; padding: 0 0;">
                        <img class="avatar w-16 h-16" src="{{ url_for('image.getAvatar', username=user.username) }}" alt="{{ _words['user_avatar'] }}">
                    </div>
                    <div class="col-md-6 d-flex flex-column justify-content-center">
                        <h6 class="card-subtitle text-muted">{{ user.username }}</h6>
                    </div>
                </div>
            </a>

            <p class="card-text text-muted small"><strong>{{ _words['created_at'] }}:</strong> {{ source.created_at.strftime('%Y-%m-%d %H:%M:%S') }}</p>
            <!-- Reaction Buttons -->
            <div class="d-flex gap-2 mt-1">
                {% for label in labels %}
                {% set fact_label = fact.labels | selectattr("label_id", "equalto", label._id) | list %}
                {% set users = fact_label[0].users if fact_label and fact_label[0].users is not none else [] %}
                {% set is_active = self_user_id in users %}
                {% set span_color = label.color %}
                    <span id="reaction-{{label.get('name')}}" class="btn btn-outline-secondary btn-sm" style="color: {{span_color}}; border-color: {{span_color}}" data-bs-toggle="tooltip" title="{{ label.name }}">
                        {{label.get('icon', label.get('name')) | safe}} {{ users | length }}
                    </span>
                    <script nonce="{{ _nonce }}">
                        document.getElementById("reaction-{{label.get('name')}}").addEventListener("click", function() {
                            sendReaction('{{ fact._id }}', 'facts', '{{label.name}}');
                        });
                    </script>
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
</div>

<!-- JavaScript for handling reactions -->
<script nonce="{{ _nonce }}">
    document.getElementById("copy-button").addEventListener("click", function() {
        copyToClipboard('{{ _host }}/facts?_id={{ fact._id }}&baked={{ fact.title }} ({{ source.author }}, {{ source.year }})', this);
    });
    function sendReaction(sourceId, collection, label) {
        fetch('{{ url_for('database.react') }}', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token() }}'
            },
            body: JSON.stringify({
                "_id": sourceId,
                "_collection": collection,
                "_label": label
            })
        })
        .then(response => response.json())
        .then(data => {
            window.location.reload();
        })
        .catch(error => {
            console.log(error);
            alert('Relogin');
        });
    }

    function copyToClipboard(text, button) {
            navigator.clipboard.writeText(text).then(function() {
                button.getElementsByTagName('p')[0].innerHTML = '{{ _words['copied'] }}';
            }).catch(function(error) {
                console.error("Copy failed", error);
            });
        }


    document.getElementById("deleteFactForm").addEventListener("submit", function(event) {
        event.preventDefault();  // Stop default submission

        let form = document.getElementById("deleteFactForm");

        let newUrl = window.location.origin + window.location.pathname + "?_id={{ fact._id }}&baked=" + '{{ fact.title }} ({{ source.author }}, {{ source.year }})';
        console.log(newUrl);
        history.pushState({}, "", newUrl);

        let formData = new FormData(this);

        fetch("{{ url_for('database.deleteFact') }}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": "{{ csrf_token() }}"  // Add CSRF token in headers
            },
            body: formData
        }).then(data => {
              window.location.reload(); // Reloads the current page
          })
    });
</script>

{% endblock %}

app/templates/profile.html
{% extends 'index.html' %}

{% block title %}Source Details{% endblock %}

{% block content %}

    <div class="container card shadow-lg p-3 mb-5 bg-light rounded">
        <div class="card-body">

            <div class="row">
                <div class="col-md-6 text-end" style="width: 64px; height: 64px; padding: 0 0;">
                    <img class="avatar" src="{{ url_for('image.getAvatar', username=user.username) }}" alt="{{ _words['user_avatar'] }}">
                </div>
                <div class="col-md-6 d-flex flex-column justify-content-center">
                    <h2 class="card-title" style="margin-bottom: 0;">{{ user.username }}</h2>
                    <h6 style="margin-bottom: 0;"><span class="badge text-white px-2 py-1 rounded" style="background-color: {{ _primary_color }};">{{ prefer_type.name }} {{ _words['mediator'] }}</span> <a href="{{redirect_manage_profile}}">{{ _words['account_console'] if not isSideProfile }}</i></a></h6>
                </div>
            </div>

            <hr>
            <h3>{{ _words['user_info'] }}</h3>
            <p><strong>{{ _words['name'] }}:</strong> {{ user.name }}</p>
            <p><strong>{{ _words['username'] }}:</strong> {{ user.username }}</p>
            <p><strong>{{ _words['email'] }}:</strong> {{ user.email }}
                {% if user.email_verified or user.emailVerified %}
                    <span class="badge bg-success">{{ _words['verified'] }}</span>
                {% else %}
                    <span class="badge bg-danger">{{ _words['not_verified'] }}</span>
                {% endif %}
            </p>
            {% if user.get('realm_access', None) %}
            <p><strong>{{ _words['roles'] }}:</strong>
                <ul>
                    {% for role in user.realm_access.roles %}
                        <li>{{ role }}</li>
                    {% endfor %}
                </ul>
            </p>

            <p><strong>{{ _words['permissions'] }}:</strong>
                <ul>
                    {% for permission in user.resource_access.get('account', {}).get('roles', []) %}
                        <li>{{ permission }}</li>
                    {% endfor %}
                </ul>
            </p>
            {% endif %}

            <p><strong>{{ _words['status'] }}:</strong>
                {% if user.enabled %}
                    <span class="badge bg-success">{{ _words['active'] }}</span>
                {% else %}
                    <span class="badge bg-danger">{{ _words['inactive'] }}</span>
                {% endif %}
            </p>
            <p><strong>{{ _words['created_at'] }}:</strong> {{ user.createdTimestamp | datetime_format }}</p>

            <hr>

            {% if patreon %}
            {% if patreon.get('data', None) %}
            <div class="card shadow-lg text-center" style="width: 24rem;">
                <img src="{{ patreon['data']['attributes']['thumb_url'] }}"
                     class="card-img-top rounded-circle mx-auto mt-3"
                     style="width: 120px; height: 120px; object-fit: cover; border: 4px solid;"
                     alt="Patreon Avatar">
                <div class="card-body">
                    <h4 class="card-title fw-bold">{{ patreon['data']['attributes']['full_name'] }}</h4>
                    <p class="text-muted">Patreon ID: <span class="fw-semibold">{{ patreon['data']['id'] }}</span></p>
                    <p class="badge bg-secondary">{{ patreon['data']['type'] | capitalize }}</p>
                </div>
            </div>
            {% else %}
                <div class="text-center mb-4">
                        <a href="{{ url_for('patreon_authentication.login') }}"
                           class="btn fw-bold px-4 py-2 shadow-lg"
                           style="color: black!important;">
                            <i class="fa-brands fa-patreon me-2"></i>Patreon
                        </a>
                    </div>
            {% endif %}
            {% endif %}

            <hr>
                <!-- Reaction Buttons -->
            <h3>{{ _words['total_labels_on_facts'] }}</h3>
            <div class="d-flex gap-2 mb-3">
                {% for label in labels %}
                    <span class="badge bg-light" style="color: #666;" data-bs-toggle="tooltip" title="{{ label.name }}">
                        {{label.get('icon', label.get('name')) | safe}} {{ label.get('reaction_count') }}
                    </span>
                {% endfor %}
            </div>
            <hr>
            <table class="table table-striped table-hover table-bordered table-responsive">
                <thead class="table-dark">
                    <tr>
                        <th>{{ _words['title'] }}</th>
                        <th>{{ _words['source'].title() }}</th>
                        <th>{{ _words['type'] }}</th>
                        <th>{{ _words['delete'] }}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fact in facts %}
                    <tr>
                        <td>
                            <a href="{{ url_for('web.factsView', _id=fact._id) }}" class="text-decoration-none fw-bold">
                                {{ fact.title }}
                            </a>
                        </td>
                        <td>
                            {% if fact.source_info %}
                                <a href="{{ url_for('web.sourcesView', _id=fact.source_info[0]._id) }}" class="">
                                    ({{ fact.source_info[0].author if fact.source_info[0].author else "N/A" }},
                                    {{ fact.source_info[0].year if fact.source_info[0].year else "N/A" }},
                                    "{{ fact.source_info[0].title if fact.source_info[0].title else "Unknown" }}")
                                </a>
                            {% else %}
                                <span class="text-muted">No source available</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if fact.source_info and fact.source_info[0].type_info %}
                                <span class="badge text-white" style="background-color: {{ fact.source_info[0].type_info[0].color }};">
                                    {{ fact.source_info[0].type_info[0].name }}
                                </span>
                            {% else %}
                                <span class="badge bg-secondary">Unknown</span>
                            {% endif %}
                        </td>
                        <td>
                            <form action="{{ url_for('database.deleteFact') }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="fact_id" value="{{ fact._id }}">
                                <button type="submit" class="btn btn-danger" style="text-decoration: none!important; color: white!important;">
                                    <i class="fas fa-times"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <hr>

            <h3>{{ _words['developer_info'] }}</h3>
            <p><strong>Client ID:</strong> {{ user.client_id }}</p>
            <p><strong>Issuer:</strong> <a href="{{ user.iss }}" target="_blank">Keycloak Realm</a></p>
            <p><strong>Token Type:</strong> {{ user.token_type }}</p>
            <p><strong>Scope:</strong> {{ user.scope }}</p>
            <p><strong>Subject (sub):</strong> {{ user.id }}</p>

            <p><strong>TOTP (2FA):</strong> {{ "Enabled" if user.totp else "Disabled" }}</p>
            <p><strong>Not Before:</strong> {{ user.notBefore }}</p>

            <p><strong>Disableable Credential Types:</strong>
                {% if user.disableableCredentialTypes %}
                    <ul>
                        {% for credential in user.disableableCredentialTypes %}
                            <li>{{ credential }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    None
                {% endif %}
            </p>

            <p><strong>Required Actions:</strong>
                {% if user.requiredActions %}
                    <ul>
                        {% for action in user.requiredActions %}
                            <li>{{ action }}</li>
                        {% endfor %}
                    </ul>
                {% else %}
                    None
                {% endif %}
            </p>

        </div>

    </div>
{% endblock %}